test linting failure

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -33,7 +33,10 @@ jobs:
         go vet ./...
 
     # Run linting
-    - name: Run linting
+    - name: Run golint
       run: |
-        go install golang.org/x/lint/golint@latest
-        golint ./...
+        golint ./... | tee lint-output.txt
+        if grep -q -e "warning" -e "error" lint-output.txt; then
+          echo "Linting errors detected"
+          exit 1
+        fi
